export default {
	REQ_ADD_USER: 'REQ_ADD_USER',
	REC_ADD_USER: 'REC_ADD_USER',
	REC_ADD_USER_ERR: 'REC_ADD_USER_ERR',
	RESET_ADD_USER: 'RESET_ADD_USER',

	REQ_REMOVE_USER: 'REQ_REMOVE_USER',
	REC_REMOVE_USER: 'REC_REMOVE_USER',
	REC_REMOVE_USER_ERR: 'REC_REMOVE_USER_ERR',
	RESET_REMOVE_USER: 'RESET_REMOVE_USER',

	REQ_GET_USER: 'REQ_GET_USER',
	REC_GET_USER: 'REC_GET_USER',
	REC_GET_USER_ERR: 'REC_GET_USER_ERR',
	RESET_GET_USER: 'RESET_GET_USER',
};
