export default {
	REQ_ADD_USER: 'REQ_ADD_USER',
	REC_ADD_USER: 'REC_ADD_USER',
	REC_ADD_USER_ERR: 'REC_ADD_USER_ERR',
	RESET_ADD_USER: 'RESET_ADD_USER',

	REQ_REMOVE_USER: 'REQ_REMOVE_USER',
	REC_REMOVE_USER: 'REC_REMOVE_USER',
	REC_REMOVE_USER_ERR: 'REC_REMOVE_USER_ERR',
	RESET_REMOVE_USER: 'RESET_REMOVE_USER',

	REQ_GET_USER: 'REQ_GET_USER',
	REC_GET_USER: 'REC_GET_USER',
	REC_GET_USER_ERR: 'REC_GET_USER_ERR',
	RESET_GET_USER: 'RESET_GET_USER',

	REQ_ADD_EMAIL: 'REQ_ADD_EMAIL',
	REC_ADD_EMAIL: 'REC_ADD_EMAIL',
	REC_ADD_EMAIL_ERR: 'REC_ADD_EMAIL_ERR',
	RESET_ADD_EMAIL: 'RESET_ADD_EMAIL',

	REQ_REMOVE_EMAIL: 'REQ_REMOVE_EMAIL',
	REC_REMOVE_EMAIL: 'REC_REMOVE_EMAIL',
	REC_REMOVE_EMAIL_ERR: 'REC_REMOVE_EMAIL_ERR',
	RESET_REMOVE_EMAIL: 'RESET_REMOVE_EMAIL',

	REQ_GET_EMAIL: 'REQ_GET_EMAIL',
	REC_GET_EMAIL: 'REC_GET_EMAIL',
	REC_GET_EMAIL_ERR: 'REC_GET_EMAIL_ERR',
	RESET_GET_EMAIL: 'RESET_GET_EMAIL',

	REQ_REMOVE_INBOX: 'REQ_REMOVE_INBOX',
	REC_REMOVE_INBOX: 'REC_REMOVE_INBOX',
	REC_REMOVE_INBOX_ERR: 'REC_REMOVE_INBOX_ERR',
	RESET_REMOVE_INBOX: 'RESET_REMOVE_INBOX',

	REQ_GET_INBOX: 'REQ_GET_INBOX',
	REC_GET_INBOX: 'REC_GET_INBOX',
	REC_GET_INBOX_ERR: 'REC_GET_INBOX_ERR',
	RESET_GET_INBOX: 'RESET_GET_INBOX',
};
